---
version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce:2.17.0
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./portainer_data:/data:rw
      - /etc/localtime:/etc/localtime:ro
...

###
# docker run 命令
###
# docker run -d \
#   --restart=always \
#   --name=portainer \
#   -p 9000:9000 \
#   -v $(pwd)/portainer_data:/data \
#   -v /etc/localtime:/etc/localtime \
#   portainer/portainer-ce:2.17.0
###
# agent 运行命令
###
# docker run -d \
#   --restart=always \
#   --name=portainer_agent \
#   -p 9001:9001 \
#   -v /var/run/docker.sock:/var/run/docker.sock \
#   -v /var/lib/docker/volumes:/var/lib/docker/volumes \
#   portainer/agent:2.17.0
###